name: Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Run Kotlin Linter
        uses: lucasnlm/ktlint-action@master
  
      - name: Run Android Linter
        run: ./gradlew lintStagingDebug
